### ISSUE TITLE
ReadyEvent not fired / fired at the wrong time

### ISSUE THREAD

**Issue by Teln0** [Discord4J/Discord4J#810] opened 2020-11-17 13:11 UTC
**To Reproduce:**
```java
import discord4j.core.DiscordClientBuilder;
import discord4j.core.GatewayDiscordClient;
import discord4j.core.event.domain.lifecycle.ReadyEvent;
import discord4j.core.object.entity.User;

public class Bot {
  public static void main(String[] args) {
    GatewayDiscordClient client = DiscordClientBuilder.create("My token is here in the actual code").build().login().block();

    client.getEventDispatcher().on(ReadyEvent.class)
        .subscribe(event -> {
          User self = event.getSelf();
          System.out.println(String.format("Logged in as %s#%s", self.getUsername(), self.getDiscriminator()));
        });

    client.onDisconnect().block();
  }
}
```

**Expected Behavior:**
I'm expecting the discord tag of the bot to be printed.

**Actual Behavior:** 
The ReadyEvent is not fired.

**Version:** 
3.2.0

**Other:**

**Comment by danthonywalker** [comment] 2020-11-17 13:14
Likely a race. Can you use `withEventDispatcher` in the gateway builder? `DiscordClient.create("token").gateway().withEventDispatcher()`

**Comment by quanticc** [comment] 2020-11-17 13:51
This suggestion can work around this issue. A fix is planned while completing #796

I'll come back to this issue once that's cleared to verify the fix

**Comment by Teln0** [comment] 2020-11-17 14:16
Ok, thank you ! I'll use 3.1.1 in the meantime

**Comment by quanticc** [comment] 2020-11-29 22:12
This is ultimately an issue caused by reactor-core: https://github.com/reactor/reactor-core/issues/2513

Confirmed it is fixed in latest snapshots, so we'll wait until their 3.4.1 release to bump our 3.2.x version and revert the workaround (default event dispatcher change)

**Comment by quanticc** [comment] 2021-03-20 17:29
Fixed via 581e099f7e5409da638438991b64335f6fe111c3

**Closed by quanticc** 2021-03-20 17:29 UTC
Labels: area/core, bug, has workaround, reactor
