### ISSUE TITLE
Forced Close Connection

### ISSUE THREAD

**Issue by ronhombre** [Discord4J/Discord4J#1206] opened 2024-05-08 15:59 UTC
**To Reproduce:** Run API calls to any (non-discord)service 160 times every 5 minutes.

**Expected Behavior:** Sending a discord message outputs a bot response in the channel. (This breaks after 2-3 cycles of 160 API calls)

**Actual Behavior:** No bot response.

```text
23:47:53.453 WARN  HttpClientConnect - [ea8ae9a2-8, L:/192.168.1.100:15160 - R:discord.com/162.159.128.233:443] The connection observed an error
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

```

**Version:** 3.2.6

**Other:**

**Comment by Azn9** [comment] 2024-05-08 16:27
"An existing connection was forcibly closed by the remote host"

This means that either Discord's server or any router in between your computer/server and Discord's server is closing the connection, this is not a Discord4J issue.

**Closed by Azn9** 2024-05-08 16:27 UTC

**Comment by ronhombre** [comment] 2024-05-08 17:24
This should be a Discord4J issue. I run a Discord.js version of the bot without any problem. It does the same thing my bot does. I even tried turning off all my firewalls. Discord4J is not able to persist the connection, it seems

**Comment by Azn9** [comment] 2024-05-08 17:50
@ronhombre Java and JavaScript are two different languages that handle exceptions and networks differently. I do not have sufficient knowledge in JS to compare them and tell you why it may work in one and not in the other. However, if that was really a D4J issue, you would see the package `com.discord4j` in the logs. Here, only netty (the network library used) appears. 
And I reiterate, the error message tells you exactly what happened, this is not a client issue but the result of the connection being closed by either Discord's server or any server in between.

**Comment by ronhombre** [comment] 2024-05-08 18:24
@Azn9 I'm migrating to JDA. If the issue persists or not, I'll let you know

**Comment by ronhombre** [comment] 2024-05-08 20:56
@Azn9 After migrating to JDA, I don't have this issue anymore. Definitely a Discord4J issue. Letting you know as I said

**Comment by ronhombre** [comment] 2024-05-08 20:57
> @ronhombre Java and JavaScript are two different languages that handle exceptions and networks differently. I do not have sufficient knowledge in JS to compare them and tell you why it may work in one and not in the other. However, if that was really a D4J issue, you would see the package `com.discord4j` in the logs. Here, only netty (the network library used) appears. And I reiterate, the error message tells you exactly what happened, this is not a client issue but the result of the connection being closed by either Discord's server or any server in between.

To be honest, I had Discord4J logs suppressed. I didn't think of checking them. It's too late now

**Comment by quanticc** [comment] 2024-05-08 21:11
Thanks. This is an external issue we can do something about. The network library is trying to reuse a connection to Discord that has been closed remotely. We're adding a default that can evict a connection so it's recreated before a component we can't control closes it. <https://github.com/reactor/reactor-netty/issues/1774#issuecomment-908066283>

**Comment by Azn9** [comment] 2024-05-08 21:41
That's just completely disrespectful. I took some of my time to answer you, and the issue is, as I said NOT caused by D4J, but by netty, which I am not a contributor of.
