### ISSUE TITLE
Bot freezes after about 100 button presses and many button presses are missed

### ISSUE THREAD

**Issue by UnorderedSigh** [Discord4J/Discord4J#1178] opened 2024-01-04 01:37 UTC
![fail](https://github.com/Discord4J/Discord4J/assets/116329264/6a839efe-cba8-4014-a1fc-e51223785f38)

**To Reproduce:**

1. This tag of this bot: https://github.com/UnorderedSigh/FreezeDiscord4J/releases/tag/failing-version
    - The code is in a `<detail>` block at the bottom of this issue description.
2. Use the `/fail` command.
3. Press the button many times.

The HEAD of master is a version from @quanticc which prevents the freeze. It still misses lots of events when the button is pressed rapidly. However, it does keep working forever. The key is to wait for the button's number to change before clicking again.

**Expected Behavior:**

Button counter increases when button is pressed. Bot does not freeze.

**Actual Behavior:**

Rapid presses result in frequent "This application did not respond" messages. These grow increasingly frequent until the bot freezes. In my last three attempts, this happened at 122, 122, and 109 successful button presses. (By that, I mean button presses where the app responded.)

The bot will freeze if you press the button less frequently. You won't get as many "This application did not respond" errors. Eventually, you will get that one last error, when the bot ceases to respond.

After the failure: According to the logs, the bot is still beating its heart. Discord also shows the bot as being logged in. The bot is not using any CPU time.

#### The log file

From hash 13f27a1 of my FreezeDiscord4J repository:

[repo-version.log](https://github.com/Discord4J/Discord4J/files/13832682/run.log)

From a version with crazy workarounds:

[crazy-workarounds.log](https://github.com/Discord4J/Discord4J/files/13832532/fail.log)

The exception at the top comes from killing gradle before starting. Not doing that has no effect on the failure. Actually, nothing I do or don't do has any effect. It fails regardless.

**Version:**

I've tried:

1. 3.2.6
2. 3.3.0-RC1
3. 3.3.0-M2

**Other:**

It *will* fail without pressing buttons. Sending lots of slash commands has the same effect. Pressing a button takes much less work, though. Easier to reproduce it that way.

I have a far more complicated bot with the same problem. In that one, I added diagnostics in the main thread. Java detects no deadlocks and ForkJoinPool.commonPool() is able to take new commands. A dump of all thread stacks shows that everyone is waiting.

Using the boundedElastic dispatcher for events did not help.

As a fallback, I was going to have the bot exit when it detected this failure condition. Then an external process would restart it. Unfortunately, I haven't found a way to detect the condition automatically. Obviously, fixing the bug or working around it would be better.

Linux:
`Linux localhost 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux`

JVM is Oracle 21:
```
java 21.0.1 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
```

Running on a virtual machine with 4 processors and 8 GB of RAM. Processors are AMD EPYC 7713 microcode 0xa0011d1.

I tried many other workarounds since I opened this issue. See the first comment.

**The Code**

<details> <summary>Taken from the repository linked at the top of this issue.</summary>

```java
package freeze.bot;

import discord4j.core.DiscordClient;
import discord4j.core.GatewayDiscordClient;
import discord4j.core.event.domain.interaction.ButtonInteractionEvent;
import discord4j.core.event.domain.interaction.ChatInputInteractionEvent;
import discord4j.core.event.domain.lifecycle.ReadyEvent;
import discord4j.core.object.component.ActionRow;
import discord4j.core.object.component.Button;
import discord4j.discordjson.json.ApplicationCommandRequest;
import discord4j.rest.RestClient;
import discord4j.rest.service.ApplicationService;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import reactor.core.publisher.Mono;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Simple {
    private static final Logger LOGGER = LoggerFactory.getLogger(Simple.class);

    public static void main(String[] args) {
        String token = null;
        try(BufferedReader reader = Files.newBufferedReader(new File("bot-token.txt").toPath())) {
            token = reader.readLine().strip();
        } catch(Exception ioe) {
            LOGGER.error("Cannot read bot token: ", ioe);
            System.exit(1);
        }
        DiscordClient.create(token).gateway()
            .withGateway(client -> client.on(ReadyEvent.class)
                        .doOnNext(ready -> withGatewayClient(client))
                        .doOnError(error -> LOGGER.error("gateway error: ", error)))
            .doOnError(error -> {
                    LOGGER.error("bot error: ", error);
                    System.exit(1);
                })
            .block();
    }

    private static Mono<Void> handleChatCommand(ChatInputInteractionEvent event) {
        try {
            String commandName = event.getCommandName();
            if(!commandName.equals("fail"))
                return event.reply("Unsupported command /"+commandName).withEphemeral(true);
            return event.reply("Press button many times to freeze bot.")
                .withComponents(ActionRow.of(Button.danger("fail:0", "freeze bot (0 presses)")));
        } catch(Exception e) {
            LOGGER.error("Unhandled exception in handleChatCommand: ", e);
            throw e;
        }
    }

    private static Mono<Void> handleButtonInteraction(ButtonInteractionEvent event) {
        try {
            String[] fields = event.getCustomId().split(":");
            String commandName = fields[0];
            int count = Integer.parseInt(fields[1]);
            if(!commandName.equals("fail"))
                return event.reply("Unsupported command /"+commandName).withEphemeral(true);
            ActionRow row = ActionRow.of(Button.danger("fail:" + (count + 1), "freeze bot (" + (count+1) + " presses)"));
            return event.deferEdit().concatWith(Mono.defer(() -> {
                        return event.editReply().withComponents(row).then();
                        })).then();
        } catch(Exception e) {
            LOGGER.error("Unhandled exception in handleButtonInteraction: ", e);
            throw e;
        }
    }

    private static void withGatewayClient(GatewayDiscordClient gateway) {
        final RestClient restClient = gateway.getRestClient();
        final ApplicationService applicationService = restClient.getApplicationService();
        final long applicationId = restClient.getApplicationId().block();
        final List<ApplicationCommandRequest> request = new ArrayList<>();
        request.add(ApplicationCommandRequest.builder()
            .name("fail").description("causes bot to freeze").dmPermission(false).build());

        applicationService.bulkOverwriteGlobalApplicationCommand(applicationId, request)
            .doOnNext(cmd -> LOGGER.info("registered /fail"))
            .doOnError(e -> {
                    LOGGER.error("could not register /fail", e);
                    System.exit(1);
                })
            .then()
            .block();

        gateway
            .on(ChatInputInteractionEvent.class, event -> handleChatCommand(event))
            .onErrorResume(e -> {
                    LOGGER.error("error in chat interaction event", e);
                    return Mono.empty();
                })
            .mergeWith(gateway.on(ButtonInteractionEvent.class, event -> handleButtonInteraction(event))
            .onErrorResume(e -> {
                    LOGGER.error("error in button interaction event", e);
                    return Mono.empty();
                }))
            .onErrorResume(e -> {
                    LOGGER.error("error in merged chat+button interaction flux", e);
                    return Mono.empty();
                })
            .then(gateway.onDisconnect())
            .block();
    }
}
```
</details>

**Comment by UnorderedSigh** [comment] 2024-01-04 15:18
On a whim, I tried:

- Upgrading reactor

```
            implementation("io.projectreactor:reactor-core:3.6.1")
            implementation("io.projectreactor.netty:reactor-netty:1.1.14")
```

- Java 17 (instead of 21)

```
java 17.0.9 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)
```

- Reorganizing my `.on(whatever)` calls

<details> <summary>rewrite of withGatewayClient</summary>

```java
    private static void withGatewayClient(GatewayDiscordClient gateway) {
        final RestClient restClient = gateway.getRestClient();
        final ApplicationService applicationService = restClient.getApplicationService();
        final long applicationId = restClient.getApplicationId().block();
        final List<ApplicationCommandRequest> request = new ArrayList<>();
        request.add(ApplicationCommandRequest.builder()
            .name("fail").description("causes bot to freeze").dmPermission(false).build());

        applicationService.bulkOverwriteGlobalApplicationCommand(applicationId, request)
            .doOnNext(cmd -> LOGGER.info("registered /fail"))
            .doOnError(e -> {
                    LOGGER.error("could not register /fail", e);
                    System.exit(1);
                })
            .then()
            .block();

        gateway.on(ChatInputInteractionEvent.class, event -> handleChatCommand(event))
            .onErrorResume(e -> {
                    LOGGER.error("error in chat interaction event", e);
                    return Mono.empty();
                }).subscribe();
        
        gateway.on(ButtonInteractionEvent.class, event -> handleButtonInteraction(event))
            .onErrorResume(e -> {
                    LOGGER.error("error in button interaction event", e);
                    return Mono.empty();
                }).subscribe();

        gateway.onDisconnect().block();
}
```

</details>

None of that helped.

**Comment by UnorderedSigh** [comment] 2024-01-04 15:38
Switching to a different computer on a different network didn't help.

**Comment by UnorderedSigh** [comment] 2024-01-04 16:09
I've added a log (debug level) of my failed run to the issue description. This is with my numerous failed workarounds (see prior message) included.

**Comment by quanticc** [comment] 2024-01-05 03:55
Hi, thanks for the detail and the example code.

I can reproduce the issue, it is caused by blocking an infinite sequence inside: 
```java
.doOnNext(ready -> withGatewayClient(client))
```

I'm still investigating so this explanation might be updated, but that blocking code is creating a backpressure scenario due to how the default EventDispatcher in D4J, which is backed by an EmitterProcessor, works.

An EmitterProcessor will send onNext signals to each subscriber, respecting the current requested value from each one and taking the lowest one. Backpressure in Reactor allows operators to tune how many onNext signals they can accept, for example in some cases this is 32, in others 256, etc. This is the initial demand of an operator and subscription.

As items are emitted **and consumed** the demand is eventually replenished, allowing the producer to send more signals. If at any point the consumption takes more time, it is replenished more slowly to avoid overwhelming a slow consumer.

To understand this internally you could add a breakpoint without suspending in EmitterProcessor:474 (reactor-core-3.4.30)
![image](https://github.com/Discord4J/Discord4J/assets/1908830/95b05ffe-989c-4f14-886c-49dad94ad5d6)
![image](https://github.com/Discord4J/Discord4J/assets/1908830/bbfc094a-df93-4624-9c14-80da02475b35)

And you can enrich each subscriber with a context to understand:
![image](https://github.com/Discord4J/Discord4J/assets/1908830/6b782afb-3b4f-4982-91fb-4075f56e1133)
![image](https://github.com/Discord4J/Discord4J/assets/1908830/c9728db3-c752-48c9-b4db-c075d9fd0ac2)

This would highlight the current demand for each subscriber:
```
242 requested by Context2{sub=ReadyEvent, discord4j.gateway=35747ce6}
249 requested by Context2{sub=handleChatCommand, discord4j.gateway=35747ce6}
249 requested by Context2{sub=handleButtonInteraction, discord4j.gateway=35747ce6}
```

In this extreme scenario, the consumption (given by doOnNext completing) never happens because the last block call in `withGatewayClient` resolves only on disconnect, therefore the initial demand is never replenished. When it hits 0, the processor is stalled, affecting all other subscribers.

```
0 requested by Context2{sub=ReadyEvent, discord4j.gateway=35747ce6}
199 requested by Context2{sub=handleChatCommand, discord4j.gateway=35747ce6}
199 requested by Context2{sub=handleButtonInteraction, discord4j.gateway=35747ce6}
```

Btw, I'm not 100% sure why it halts around 122, my guess is that each button press emits 2 events, making it closer to 256, the initial demand I'm seeing.

Pretty sure this can be improved in D4J, either by adding docs, migrating away from EmitterProcessor and preventing this scenario somehow. Updating your code to a non blocking approach should be a start for now:

```java
public static void main(String[] args) {
	DiscordClient.create(System.getenv("TOKEN"))
		.gateway()
		.withGateway(client -> client.on(ReadyEvent.class)
			.flatMap(__ -> withGatewayClient(client))
			.doOnError(error -> LOGGER.error("gateway error: ", error)))
		.doOnError(error -> {
			LOGGER.error("bot error: ", error);
			System.exit(1);
		})
		.block();
}
```
```java
private static Mono<Void> withGatewayClient(GatewayDiscordClient gateway) {
	// (...)

	return gateway
		.on(ChatInputInteractionEvent.class, event -> handleChatCommand(event))
		.onErrorResume(e -> {
			LOGGER.error("error in chat interaction event", e);
			return Mono.empty();
		})
		.mergeWith(gateway.on(ButtonInteractionEvent.class, event -> handleButtonInteraction(event))
			.onErrorResume(e -> {
				LOGGER.error("error in button interaction event", e);
				return Mono.empty();
			}))
		.onErrorResume(e -> {
			LOGGER.error("error in merged chat+button interaction flux", e);
			return Mono.empty();
		})
		.then();
}
```
Also we typically use Mono.when to add up multiple sources:
```java
Mono.when(
            gateway.on(ChatInputInteractionEvent.class, event -> handleChatCommand(event)),
            gateway.on(ButtonInteractionEvent.class, event -> handleButtonInteraction(event))
        ) // ...
```

I tried it and should work for you too, as the doOnNext is not held back by an "infinite" sequence. Hope this also helps with your actual bot code.

**Comment by UnorderedSigh** [comment] 2024-01-05 14:49
I updated the master of the bot to contain @quanticc's fixes. The https://github.com/UnorderedSigh/FreezeDiscord4J/releases/tag/failing-version tag contains the original version which broke.

The bot still misses many events if the button is pressed too quickly. You must press the button before the number increments to see it happen.

**Comment by quanticc** [comment] 2024-01-05 16:48
Interactions in the client work by including the custom_id somewhere in the payload. I guess if you edit the custom_id in your code on click like `fail:N+1` it can cause your interaction to fail if it doesn't match after it was edited.

I've noticed when it does it's a "Component validation failed" error from Discord. If you see that error in your client, D4J doesn't get the event.

You could avoid changing the button's custom_id on click, if it's constant spam clicking is much more reliable.

Otherwise, and if your interaction takes <3 seconds, call edit directly like: `return event.edit().withComponents(row).then();`. It can speed up the process and reduce the time it takes to update the custom_id.

**Comment by UnorderedSigh** [comment] 2024-01-05 16:51
The full-sized bot never changes the button IDs. I rarely see any missed events. Your explanation seems to match the evidence.

**Comment by UnorderedSigh** [comment] 2024-01-05 16:51
My troubles are gone now, so the issue is gone from my point of view.

Do you want me to close this issue? Or leave it open as a placeholder for "need better documentation?"

**Comment by quanticc** [comment] 2024-01-05 17:04
Glad to know that. I'm closing this for now and add a bit of javadocs when I get the chance:

- `withGateway` should clearly mention that onDisconnect is included. Standalone onDisconnect is used mostly when you call `login().block()` and need something to avoid the JVM from exiting after login
- `on()` should discourage blocking for a long time, because it can create backpressure issues that affect any EventDispatcher subscription

**Closed by quanticc** 2024-01-05 17:04 UTC
