### ISSUE TITLE
"Failed to release a message" warnings when receiving audio

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#495] opened 2019-02-16 19:44 UTC
**To Reproduce:**
1. Join a voice channel as an user
2. Make the bot joins
3. Play music using lavaplayer (thanks @kvnxiao) 
4. Speak as an user

**Expected Behavior:** No warning

**Actual Behavior:**
Failed to release a message: DatagramPacket: https://pastebin.com/aTYGtX8E

**Version:** V3.0.2

**Additional information:**
WinteryFox#0001 has experienced a similar issue, but I cannot reproduce:
Failed to release a message: BinaryWebSocketFrame: https://pastebin.com/rUpd5DbJ

**Comment by quanticc** [comment] 2019-02-16 22:32
First stack trace is caused by voice receive actually, because we use Unpooled allocator for our VoiceSendTask. We might need to call `.retain()` somewhere.

The second one could be fixed in the same way. Would be good to find a way to reproduce this.

**Comment by Shadorc** [comment] 2019-02-18 15:28
I have updated the issue.
I confirm that the first stack trace is caused by the bot receiving audio. 
I can't reproduce the second one.

**Comment by kvnxiao** [comment] 2019-04-04 02:40
Also reproduced on my end when using lavaplayer && bot receives audio from another user:

```java
WARN  | [udp-epoll-2] [i.n.u.ReferenceCountUtil]:L115 : Failed to release a message: DatagramPacket(/162.245.206.141:51439 => /192.168.0.29:41806, PooledUnsafeDirectByteBuf(freed))
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.toLiveRealCnt(AbstractReferenceCountedByteBuf.java:181)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:133)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:124)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	at io.netty.channel.DefaultAddressedEnvelope.release(DefaultAddressedEnvelope.java:101)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:166)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:484)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

on reactor-netty 0.8.5-RELEASE and base netty 4.1.33.Final

**Comment by kvnxiao** [comment] 2019-04-04 02:43
I cannot reproduce the steps outlined in the original issue post, as it seems that I _MUST_ be playing music through lavaplayer and only then will this warning message show up if I decide to speak while the bot is playing.

**Comment by SizableShrimp** [comment] 2019-04-04 05:44
Can reproduce with the steps that @kvnxiao said on `3.0.1`. Could not reproduce on commit `ff71ca38abfec9c3d459db132b8c7892df6393f7` (what my bot was previously using). Will test the fix branch

**Comment by quanticc** [comment] 2019-04-04 19:31
@Shadorc @kvnxiao @SizableShrimp can you test latest snapshot `b358826`

**Comment by Shadorc** [comment] 2019-04-04 21:01
The issue is still present

**Comment by SizableShrimp** [comment] 2019-04-05 02:36
I can also confirm that the issue persists in commit `d374d35`.

**Comment by quanticc** [comment] 2019-04-12 06:55
The warning you currently receive means the resource is trying to be cleaned up after it was consumed. There are no other effects besides the log spam.

It is commonly fixed by checking the if refCnt > 0 before releasing, but we don't control that portion of the code.

**Comment by quanticc** [comment] 2019-04-21 20:17
I'm investigating this issue again. The exception means that we shouldn't let netty prematurely reclaim the buffer so we should call .retain() on it.

I've updated this in `70f2644`. @kvnxiao @Shadorc @SizableShrimp If you have feedback that reproduces this problem or discover the opposite one (LEAK: ....) please provide instructions to replicate or code. So far I've been unable to reproduce with 2 bots playing to the same channel + 1 additional user speaking.

**Comment by Shadorc** [comment] 2019-04-28 17:57
Issue still present
https://pastebin.com/kdN0H4e7

**Comment by quanticc** [comment] 2019-05-01 20:30
Thanks to @kvnxiao we discovered that this is a bug on our side triggered by using a no-op AudioReceiver (or not setting one while connecting). Will be deploying a fix soon.

**Closed** 2019-05-01 22:16 UTC
Labels: bug, voice
