### ISSUE TITLE
Implement User Connections

### ISSUE THREAD

**Issue by p4czyk** [Discord4J/Discord4J#828] opened 2020-12-31 16:31 UTC
**Feature Description:** I just have searched something in the Discord Developer Documentation and found that 🔍. I think there is no implementation of the User Connections to services such as YouTube, Twitch or GitHub in the REST module of the repository 📚. So the UserData (https://javadoc.io/doc/com.discord4j/discord-json/latest/discord4j/discordjson/json/UserData.html) should have some kind of a list where the User Connections (https://discord.com/developers/docs/resources/user#connection-object) are delivered. 📬 What do you think about that? 🤔

**Justification:** https://discord.com/developers/docs/resources/user#get-user-connections

**Comment by danthonywalker** [comment] 2020-12-31 16:36
User connections are behind OAuth, which is outside the scope for D4J

That said, we do plan on adding some OAuth capability in the future. Considering Slash Commands requires us to have a web server, OAuth then is well within scope and capability. But this is not a priority.

So I'll keep this open for now.

**Comment by p4czyk** [comment] 2020-12-31 16:50
> User connections are behind OAuth, which is outside the scope for D4J
> 
> That said, we do plan on adding some OAuth capability in the future. Considering Slash Commands requires us to have a web server, OAuth then is well within scope and capability. But this is not a priority.
> 
> So I'll keep this open for now. 

Okay, thank you @danthonywalker . 👓 I didn't noticed that. 🙆‍♂️ I am interested in how this will be implemented in the future. 🚀

**Comment by darichey** [comment] 2021-04-18 18:58
Is this a duplicate of #715 ?

**Closed** 2023-06-05 05:34 UTC
Labels: feature-request
