### ISSUE TITLE
getMessagesAfter and getMessagesBefore seem to be in reverse.

### ISSUE THREAD

**Issue by std46** [Discord4J/Discord4J#724] opened 2020-06-13 04:27 UTC
**To Reproduce:** 
See MessageChannel.getMessagesAfter and MessageChannel.getMessagesBefore

**Expected Behavior:** 

If a user sends a command and I call MessageChannel.getMessagesBefore(Snowflake messageId) ,where messageId is the id from the requesting command, I would expect the to receive messages that were sent before the requesting command.

**Actual Behavior:** 
Nothing. I have to call MessageChannel.getMessagesAfter. The result being I'm sent messages that were sent before the id I send to MessageChannel.getMessagesAfter,

**Version:** 
3.0.14 - latest on maven.

**Comment by quanticc** [comment] 2020-06-14 03:07
Could you give us more detail about the code you're using to call `getMessagesBefore` ?

Discord4J doesn't perform much more than wrapping over the results from the API. Where we pass `before` from that method, and `after` from `getMessagesAfter`.

https://discord.com/developers/docs/resources/channel#get-channel-messages

**Comment by darichey** [comment] 2020-06-17 19:33
Here's an example program that successfully prints the content of the message prior to me sending "!test"
```java
DiscordClient client = DiscordClient.create("token");
client.getEventDispatcher().on(MessageCreateEvent.class)
        .map(MessageCreateEvent::getMessage)
        .filter(msg -> msg.getContent().map("!test"::equals).orElse(false))
        .flatMap(msg -> msg.getChannel().flatMap(channel -> channel.getMessagesBefore(msg.getId()).next()))
        .map(Message::getContent)
        .subscribe(System.out::println);
client.login().block();
```

**Comment by quanticc** [comment] 2020-07-27 05:26
Closing this as the method works as intended

**Closed by quanticc** 2020-07-27 05:26 UTC
Labels: for user attention
