### ISSUE TITLE
Error when retriving the region name of a guild

### ISSUE THREAD

**Issue by Dawoox** [Discord4J/Discord4J#999] opened 2021-09-04 12:32 UTC
**To Reproduce:**
Where event is a MessageCreateEvent
```java
event.getGuild().block().getRegion().block().getName()
``` 

**Expected Behavior:**
Return the guild region name.

**Actual Behavior:**
```java
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableRegionData`, problem: Cannot build RegionData, some of required attributes are not set [vip]
 at [Source: (byte[])"[{"id": "us-west", "name": "US West", "custom": false, "deprecated": false, "optimal": false}, {"id": "us-east", "name": "US East", "custom": false, "deprecated": false, "optimal": false}, {"id": "us-central", "name": "US Central", "custom": false, "deprecated": false, "optimal": false}, {"id": "us-south", "name": "US South", "custom": false, "deprecated": false, "optimal": false}, {"id": "singapore", "name": "Singapore", "custom": false, "deprecated": false, "optimal": false}, {"id": "southafri"[truncated 729 bytes]; line: 1, column: 93] (through reference chain: java.lang.Object[][0])
    at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74)
    Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
    |_ checkpoint ⇢ Body from GET /guilds/714164965539446785/regions [ClientResponse]
```

**Version:**
Test on : v3.1.7 and v3.2.0-RC3

**Other:** 
Seems like a new bug, this feature was working for me 3 months ago and stop working without any code change.
(Sorry if the issue is not containing not enough infos it's the first time i'm doing this kind of stuff)

**Comment by WeeskyBDW** [comment] 2021-09-04 13:03
Your issue is caused by a Discord API change. Now, regions are channels based and you cannot set guild region as global region for voice channels

**Comment by NovaFox161** [comment] 2021-09-04 16:32
> Your issue is caused by a Discord API change. Now, regions are channels based and you cannot set guild region as global region for voice channels
> 
> In your context, no alternative is possible

This isn't fully accurate. Specific guild region is no longer global and is per-channel, but the endpoint this code is hitting returns all regions the guild may use.

It appears however that the `vip` field is being sent optionally from this endpoint even though its not marked as being optional (in d4j terms, its a Possible). However, when getting the voice region on a specific channel, this appears to not be the case and there are no errors logged.

I'm not sure how the other maintainers would like to address this.

**Comment by darichey** [comment] 2021-09-07 17:56
Related to https://github.com/discord/discord-api-docs/issues/3603. No response from Discord. I guess we should for now mark this property as optional.

**Closed** 2021-09-08 03:03 UTC
Labels: bug, discord, has workaround
