### ISSUE TITLE
ImmutableMessageReactionAdd error for message author

### ISSUE THREAD

**Issue by jwc65** [Discord4J/Discord4J#1273] opened 2024-08-24 21:07 UTC
**To Reproduce:** 
Not entirely sure when it's caused, from just visual inspection on reaction add, but not all occurances

**Expected Behavior:** 

**Actual Behavior:** 

20:57:49.359 WARN  [or-http-epoll-3] load.JacksonPayloadReader : Error while decoding JSON (com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.gateway.ImmutableMessageReactionAdd`, problem: Cannot invoke "discord4j.discordjson.Id.asLong()" because "messageAuthorId$impl" is null
bot-conquest-discord-1-1  |  at [Source: UNKNOWN; byte offset: #UNKNOWN]): {"t":"MESSAGE_REACTION_ADD","s":114049,"op":0,"d":{"user_id":"1275624198425018378","type":0,"message_id":"1074885155937853440","member":{"user":{"username":"schmeebus1","public_flags":0,"id":"1275624198425018378","global_name":"Schmeebus1","display_name":"Schmeebus1","discriminator":"0","clan":null,"bot":false,"avatar_decoration_data":null,"avatar":"420d285f3ae7654fc7cbbf02385c2c78"},"roles":["545276190307647488","1177662596082581514","507792886428073998"],"premium_since":null,"pending":false,"nick":null,"mute":false,"joined_at":"2024-08-24T20:57:27.962000+00:00","flags":0,"deaf":false,"communication_disabled_until":null,"banner":null,"avatar":null},"emoji":{"name":"💁","id":null},"channel_id":"510612409384304640","burst":false,"guild_id":"505974446914535426"}}

**Version:** 

3.3.0-SNAPSHOT

**Other:**

**Comment by Doc94** [comment] 2024-08-24 21:36
Caused by discord-json missing a change where the author id can not be passed in the event (https://github.com/discord/discord-api-docs/commit/26b95485354b4d583b35f6dd5b149d1ab0ff42ae)

**Comment by Doc94** [comment] 2024-11-17 01:23
Fixed in https://github.com/Discord4J/Discord4J/commit/78a89198708e0285076f42be8cbcbeb853684bd2

**Closed by Doc94** 2024-11-17 01:23 UTC
Labels: bug
