### ISSUE TITLE
Implement context menus

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#983] opened 2021-08-10 21:51 UTC
See: https://github.com/discord/discord-api-docs/pull/3614

I think this will involve many other changes to the existing slash command stuff. That should be fine to break in 3.1 since they are experimental.

**Comment by NovaFox161** [comment] 2021-09-04 02:11
So, discord shoehorned all of this into the same system and there's inconsistently applied rules for these now.

* There's the possible `type` integer field.
  * defaults to 1, a slash command, when not provided.
  * 2 and 3 are user and message commands respectively.
  * These are now grouped together as "Application Commands" and the "slash command" naming is dropping in favor of "chat input command type"
* `options` field is not allowed on message/user commands.
* `description` field is not allowed on user/message commands when creating them **but** will return an empty string when fetching commands.
* The name regex only applies to chat input commands. Message/User commands only have the name length limit
  * This isn't clearly documented, but their examples show the regex not applying to those 2 types while still requiring the length limit.
  * I've confirmed this in DAPI as well.
* Discord unofficially announced they will return message data for ephemeral messages now, but its still marked as nullable in the docs. I assume because user commands and maybe future types of interactions will not be tied to messages.
  * So this means previous commits to change that field to a JsonNode should be reverted as, if the field is present, it should be a full message object.

**Comment by NovaFox161** [comment] 2021-09-24 21:49
Now fully implemented

**Closed by NovaFox161** 2021-09-24 21:49 UTC
Labels: discord, feature-request, area/rest, area/gateway, area/core, area/data
