### ISSUE TITLE
AudioReceive Throws Exceptions

### ISSUE THREAD

**Issue by danthonywalker** [Discord4J/Discord4J#358] opened 2017-10-12 14:47 UTC
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already (although this similar to Issue #354)

### Description
Whenever the bot is playing sound or if it receives sound it throws a bunch of exceptions to the console.

### Steps to Reproduce
1. Run TestBot
2. Have it join a voice channel
3. Speak and/or have it play audio via `.play`

...

**Expected behavior:** Doesn't spam the console with a million exceptions.

**Actual behavior:** Spams the console with a million exceptions.

**Stacktrace (if applicable):**
![hover](https://media.discordapp.net/attachments/210938552563925002/368037852858023947/Capture.PNG)

**Version affected:** 2.9.1

### Additional Information
The bot can play audio just fine, it seems to just be receiving that's the issue. If this is the case then it's more than likely audio receiving events are entirely broken.

**Comment by FusionLord** [comment] 2017-10-13 12:55
As the creator of #354 and the initial reported of this very issue, I as well cannot reproduce now.

**Comment by Yeregorix** [comment] 2017-10-15 09:56
I can confirm that I have exactly the same issue with my own bot.

**Comment by Mulderd015** [comment] 2017-10-23 15:41
I have the exact same problem with my bot

**Comment by GrandPanda** [comment] 2017-10-23 19:12
As I have indicated already, I am unable to reproduce either of the exceptions. If anyone would like to provide more information on the circumstances in which the error occurs, feel free.

**Comment by Mulderd015** [comment] 2017-10-23 21:20
Everything I know:
Both exceptions occur once every few seconds.

java.lang.IllegalStateException: Invalid encryption!:
Starts after I let my bot join a voice channel.
Stops after disconnecting from the voice channel.

java.lang.IllegalStateException: Cipher too small!
Starts after I let the bot play a (youtube) song.
Does not stop after the end of the song or skipping the song with no more songs to play.
Stops after disconnecting from the voice channel.

Feel free to use my bot for testing this bug: https://github.com/Mulderd015/Inkaybot
It's far from finished, but I hope it can help you.

Bot token: DiscordBot class in the token variable.

commands:
!join
!play URL
!leave

Shutting the bot down: type a character in the console and press enter (I was lazy, sorry :P)
Atm I'm running it via IntelliJ, I havn't configured it propperly to compile to a working jar file.
The logger doesn't work, it's something I still have to fix.

**Comment by xaanit** [comment] 2017-10-23 21:28
Can't reproduce with the above bot.

**Comment by TreyRuffy** [comment] 2017-10-24 01:45
I have encountered this same error. I have done nothing besides having the bot join two discord channels (which was executed perfectly) then joining the channel. Keep in mind, I have not even forced the bot to say anything; it will just occur.
[Pastebin](https://pastebin.com/HYWhfpB4)

**Comment by danthonywalker** [comment] 2017-10-24 02:01
Video demonstration: https://giant.gfycat.com/OccasionalWelltodoIndianrhinoceros.webm

**Comment by GrandPanda** [comment] 2017-11-04 17:33
I tried to do the same steps and it works fine. Am I doing something differently? https://i.imgur.com/j0s0QWM.gifv

**Comment by austinv11** [comment] 2017-11-21 21:20
It is possible this has been fixed in 4559f14, it would be great if someone can confirm this.

**Comment by bloxgate** [comment] 2017-12-21 16:49
I'm still having this issue. It only occurs when I have the bot running on a server, when I test locally in IntelliJ with my own machine it doesn't occur.

Perhaps its a problem with the server not having the ability to play any sounds in the first place?

**Closed** 2019-03-04 23:33 UTC
Labels: cannot reproduce, v2
